site:
  name: Calendarios Repro Disseny
  site: 'https://calendarios.reprodisseny.com'
  base: '/'
  trailingSlash: false
  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
  title:
    default: 'Calendarios Personalizados para Empresas - Repro Disseny'
    template: '%s — Repro Disseny'
  description: 'Calendarios personalizados para empresas y particulares. Diseños a medida para destacar tu marca y mejorar la planificación anual.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: 'Calendarios Personalizados para Empresas'
    images:
      - url: 'https://calendarios.reprodisseny.com/assets/images/calendarios/SobremesaHome.jpg'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@reprodisseny'
    site: '@reprodisseny'
    cardType: summary_large_image

i18n:
  language: es
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6
    post:
      isEnabled: true
      permalink: '/%slug%' # Puedes usar variables como %slug%, %year%, etc.
      robots:
        index: true
    list:
      isEnabled: true
      pathname: 'blog' # Ruta principal del blog, puedes cambiarlo
      robots:
        index: true
    category:
      isEnabled: true
      pathname: 'category' # Ruta principal de categorías
      robots:
        index: true
    tag:
      isEnabled: true
      pathname: 'tag'
      robots:
        index: false
    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: 'G-302RJDGZTB' # ID de Google Analytics

ui:
  theme: 'system' # Opciones: "system" | "light" | "dark" | "light:only" | "dark:only"
